### PR TITLE
Added Cad models to the final DD Coil Design

### PR DESCRIPTION
**Pull request by avan411**

### CODE REVIEW

**Comment by Kingston802** [comment]
image
Your files are in imperial...

**Comment by avan411** [comment]
> image Your files are in imperial...

I shall change that. Thank you, Alex.
I will change the background as well.

**Review by Kingston802 — CHANGES_REQUESTED** [review]
Looks pretty good. For the terminals, if my conversions from imperial (grr you made me do maths) are correct then you only have 0.01mm of tolerance in the x direction which is probably not enough. You have plenty in the y direction though so maybe even that out. Once you change it to metric, I am happy to merge it as a draft.

**Review by Kingston802 — APPROVED** [review]
Looks good to me. Thanks Ashley.

**Pull request merged**
